In [2]:
import pandas as pd

In [29]:
address = pd.read_json('../available_data/address.json', lines=True)

In [30]:
answers = pd.read_json('../available_data/answers.json', lines=True)

In [32]:
comments = pd.read_json('../available_data/comments.json', lines=True)

In [33]:
data = pd.read_json('../available_data/data.json', lines=True)

In [34]:
history = pd.read_json('../available_data/history.json', lines=True)

In [35]:
signal = pd.read_json('../available_data/signal.json', lines=True)

In [36]:
status = pd.read_json('../available_data/status.json', lines=True)

In [37]:
address

,number,title,geolocation,address,district,zone,url
0,300000,Паркиране върху тротоар,"[42.6406533748732,23.3679667855068]","ж.к. Младост 2 250, 1799 ж.к. Младост 2, София...",район Младост,,https://call.sofia.bg/bg/Signal/Details/300000
1,300001,Цирк.Улица по която може да мине само една кол...,"[42.671637968344,23.2905499890625]","ул. „Солун“ 56, 1680 ж.к. Красно село - кв. Бо...",район Красно село,,https://call.sofia.bg/bg/Signal/Details/300001
2,300002,"Дървото е джанка и се намира до задния вход ""Ж...",,,,,https://call.sofia.bg/bg/Signal/Details/300002
3,300003,Неправилно паркиране,"[42.6406664796667,23.367980797317]","ж.к. Младост 2 250, 1799 ж.к. Младост 2, София...",район Младост,,https://call.sofia.bg/bg/Signal/Details/300003
4,300004,Опасен за движението участък с много дълбоки д...,,,,,https://call.sofia.bg/bg/Signal/Details/300004
...,...,...,...,...,...,...,...
47089,350012,Сигнал №348881/ СОА22-КЦ01-49676/ 14.10.2022,"[42.7051301550342,23.3176856833394]","бул. „Христо Ботев“ 703, 1303 София център, Со...",район Възраждане,,https://call.sofia.bg/bg/Signal/Details/350012
47090,350013,Излязъл от употреба автомобил,,,,,https://call.sofia.bg/bg/Signal/Details/350013
47091,350014,Излязъл от употреба автомобил,,,,,https://call.sofia.bg/bg/Signal/Details/350014
47092,350015,Голямо запрашаване на въздуха вследствие на на...,,,,,https://call.sofia.bg/bg/Signal/Details/350015
47093,350016,всеки ден автомобили са паркирани в нарушени н...,"[42.7178585,23.2555688]","улица „арх. Георги Ненов“ 36, София, България",район Люлин,,https://call.sofia.bg/bg/Signal/Details/350016

In [38]:
answers

       number                                            answers
0      300000                                                 []
1      300001                                                 []
2      300002                                                 []
3      300003                                                 []
4      300004  [{'documents': 'Няма', 'registration_date': '1...
...       ...                                                ...
47104  350027                                                 []
47105  350028                                                 []
47106  350029                                                 []
47107  350030                                                 []
47108  350031  [{'documents': 'Няма', 'registration_date': '2...

[47109 rows x 2 columns]

In [47]:
comments

      number comment_details comment_description
0     300001      patanasova
1     300029      gkalkovska
2     300116     vmomchilova
3     300124     vmomchilova
4     300158      edimitrova
...      ...             ...                 ...
1817  348593    lpatrashkova
1818  348629    lpatrashkova
1819  348630    lpatrashkova
1820  348635    lpatrashkova
1821  348750    lpatrashkova

[1822 rows x 3 columns]

In [40]:
data

,number,url,title,description
0,300000,https://call.sofia.bg/bg/Signal/Details/300000,Паркиране върху тротоар,Системно паркиране върху тротоара се забелязва...
1,300001,https://call.sofia.bg/bg/Signal/Details/300001,Цирк.Улица по която може да мине само една кол...,След подадени два сигнала до Районната админис...
2,300002,https://call.sofia.bg/bg/Signal/Details/300002,"Дървото е джанка и се намира до задния вход ""Ж...",
3,300003,https://call.sofia.bg/bg/Signal/Details/300003,Неправилно паркиране,Неправилно паркирали авмотобили на пътното пла...
4,300004,https://call.sofia.bg/bg/Signal/Details/300004,Опасен за движението участък с много дълбоки д...,В участък от макс. 100м има няколко мн опасни ...
...,...,...,...,...
47088,350011,https://call.sofia.bg/bg/Signal/Details/350011,Невъзтановена пътна настилка в локалното на Со...,Невъзтановена пътна настилка в локалното на Со...
47089,350012,https://call.sofia.bg/bg/Signal/Details/350012,Сигнал №348881/ СОА22-КЦ01-49676/ 14.10.2022,"Здравейте,"
47090,350013,https://call.sofia.bg/bg/Signal/Details/350013,Излязъл от употреба автомобил,
47091,350014,https://call.sofia.bg/bg/Signal/Details/350014,Излязъл от употреба автомобил,
47092,350015,https://call.sofia.bg/bg/Signal/Details/350015,Голямо запрашаване на въздуха вследствие на на...,"Здравейте,"

In [41]:
history

       number                                            history
0      300000  [{'timestamp_from': '18.01.2022 08:50', 'times...
1      300001  [{'timestamp_from': '12.01.2022 10:45', 'times...
2      300002  [{'timestamp_from': '17.01.2022 08:42', 'times...
3      300003  [{'timestamp_from': '22.02.2022 16:16', 'times...
4      300004  [{'timestamp_from': '12.01.2022 10:08', 'times...
...       ...                                                ...
47097  350020  [{'timestamp_from': '21.11.2022 09:38', 'times...
47098  350021  [{'timestamp_from': '03.11.2022 13:03', 'times...
47099  350022  [{'timestamp_from': '14.12.2022 16:07', 'times...
47100  350023  [{'timestamp_from': '02.11.2022 13:28', 'times...
47101  350024  [{'timestamp_from': '12.11.2022 07:15', 'times...

[47102 rows x 2 columns]

In [42]:
signal

,signal,category,sub_category,extraction_time
0,Сигнал №300000/ Към СОА22-КЦ01-984-[1]/ 12.01....,Паркиране /,Неправилно паркирали автомобили на пътното пла...,NaN
1,Сигнал №300001/ СОА22-КЦ01-1915/ 12.01.2022 10...,Пътна сигнализация /,Липсваща или избледняла пътна маркировка; несъ...,NaN
2,Сигнал №300002/ СОА22-КЦ01-1901/ 12.01.2022 10...,Екология. Зелена система /,Изсъхнали/неподрязани дървета и клони.,NaN
3,Сигнал №300003/ СОА22-КЦ01-1902/ 12.01.2022 10...,Паркиране /,Неправилно паркирали автомобили на пътното пла...,NaN
4,Сигнал №300004/ Към СОА22-КЦ01-1351-[1]/ 12.01...,Пътна инфраструктура /,"Дупки, пропадане или издигане на настилката на...",NaN
...,...,...,...,...
47098,Сигнал №350021/ СОА22-КЦ01-50787/ 20.10.2022 1...,"Спортни терени, площадки и съоръжения /","Амортизирани, повредени или в опасно състояние",2023-06-24_16-19-51
47099,Сигнал №350022/ СОА22-КЦ01-50788/ 20.10.2022 1...,Паркиране /,Неправилно паркирали автомобили на пътното пла...,2023-06-24_16-19-51
47100,Сигнал №350023/ СОА22-КЦ01-50795/ 20.10.2022 1...,"Търговия, реклама и преместваеми обекти /",Оплаквания срещу търговски обекти за вдигане ...,2023-06-24_16-19-51
47101,Сигнал №350024/ СОА22-КЦ01-50789/ 20.10.2022 1...,Пътна инфраструктура /,Некачествено извършвани строително -ремонтни р...,2023-06-24_16-19-51
47102,Сигнал №350025/ СОА22-КЦ01-50790/ 20.10.2022 1...,Сгради/строежи /,Шум/вибрации от строителен обект,2023-06-24_16-19-51

In [43]:
status

       number                                              title status user
0      300000                            Паркиране върху тротоар
1      300001  Цирк.Улица по която може да мине само една кол...
2      300002  Дървото е джанка и се намира до задния вход "Ж...
3      300003                               Неправилно паркиране
4      300004  Опасен за движението участък с много дълбоки д...
...       ...                                                ...    ...  ...
47066  349989                           неработещи лампи от 1,5г
47067  349990                     Изоставен или краден Автомобил
47068  349991                                Изоставен автомобил
47069  349992                 Бездомен човек на Стадион Раковски
47070  349993                                 изгорял автомобил.

[47071 rows x 4 columns]